services:
  - type: web
    name: email-classifier-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Dashboard.py --server.port=$PORT --server.address=0.0.0.0
